services:
  addon-sport-live-stremio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7777:7777
    environment:
      - NODE_ENV=production
      - ADDON_PORT=7777
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7777/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
